### PR TITLE
Update duckyinpython.py

### PR DESCRIPTION
**Pull request by mexifivehd**

### CODE REVIEW

**Comment by dbisu** [comment]
I am unlikely to merge this pull request.  Look at the changes on the Kronos branch for the likely path for including non-US keyboard layouts.

**Comment by peterfritz** [comment]
Why would it default to DE instead of US?

**Comment by Timovl** [comment]
where can I download the DE layout?

**Comment by dbisu** [comment]
@Timovl Check out Issue #10 and the kronos branch.

**Comment by dbisu** [comment]
closing pull request.  follow issue #10 for changes to support non-US keyboards.

**Pull request closed without merging**
