### PR TITLE
Payload selector

### PR DESCRIPTION
**Pull request by TheExpertNoob**
Moved "setup mode" to GP9.  
Moved  "disable usb mass storage" to GP10.  
In junction with a SPDT slider switch, this will  
disable usb mass storage and enable payload run  
or  
enable usb mass storage and disable payload (for editing).  
  
Increased the number of payloads that can be chosen (16 total) by switching to a [rotary dip switch](https://www.digikey.com/en/products/detail/nidec-copal-electronics/SH-7050MC/2057879) and wiring it up to GP2-GP5 with some DIRTY binary if statements. Someone else better at python than I could probably clean it up. Tested and works.

### CODE REVIEW

**Comment by d3k4-k3rb3r0s** [comment]
I just added slideswitches to the original pads to turn on/off usb stealth and setup mode. Felt accomplished. Came and saw this. 

Good job, ordering parts to play with it now.

**Comment by TheExpertNoob** [comment]
Well the rotary dip switch I used to test with, the one I linked, has already had two of its pins break from just the vibration of carrying it in my pocket (enclosed in a shell). So I'm still looking into the best rotary dip switch and best wat to secure it would be.
My next design will use the [563-1215-1-ND](https://www.digikey.com/en/products/detail/nidec-copal-electronics/SH-7050TB/2057874) from Digikey, I'll secure the switch with some E6000 right on top of the raspberry logo and use GP13,14,17,18 with the GNDs between them this time. and make a cutout for the rotary dip switch in the case on top instead of the side. Test it, and cover all the wires in epoxy.

**Comment by dbisu** [comment]
If you look in the board_design branch, I have the schematic and board layout I used.  I used a 4 position slide switch for payload selection.  It was Digi-key part CKN10368-ND.

**Comment by TheExpertNoob** [comment]
OOF!
They don't exactly have a rotary DIP switch, but this may help in debugging and consolidating code.
https://wokwi.com/projects/340275768135254611

**Comment by TheExpertNoob** [comment]
Got some help over [here](https://github.com/todbot/circuitpython-tricks/issues/8).

**Pull request closed without merging**
